import sys

if len(sys.argv) < 3:
    printf("Expand a map generated by FED to two byte format")
    print("usage: ", sys.argv[0:], " <infile> <outfile>")
    exit()

infile = sys.argv[1]
outfile = sys.argv[2]

with open(infile, "rb") as in_binfile:
    data = in_binfile.read()

with open(outfile, "wb") as out_binfile:
    for item in data:
        arr = bytearray([item, 0])
        out_binfile.write(arr)
